[package]
name = "fett-helmet-pi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
async-std = "1.12.0"
indicatif = "0.17.8"
png = "0.17.13"
serialport = "4.3.0"
tide = "0.16.0"
